# This file contains lists of terms that are refrenced by other scripts
# Terms will be added/removed from the lists based on the quality of results

removeWords = ["Disease-Specific",
               "Disease Specific",
               "General Research Use",
               "GRU",
               "Non-Profit Use",
               "Non Profit Use",
               "Not for Profit Use",
               "Publication",
               "Required",
               "Exchange Area",
               "NPU",
               "GSO",
               "IRB",
               "RD",
               "MDS",
               "PUB",
               "PLCO",
               "EAGLE",
               "COL",
               "LC",
               "methods",
               "or",
               "in",
               "all",
               "age",
               "groups",
               "other",
               "adults",
               "to",
               "use by PAGE study investigators only",
               "None",
               "Unrestricted",
               "No data use restrictions",
               "Up for a Challenge",
               "its",
               "multiple",
               "And",
               "with",
               "Related",
               "Conditions",
               "Only",
               "of",
               "No Insurance companies employers the police until by court order by law",
               "Research",
               "use by Finnish Familial Dyslipedemia study investigators",
               "Patenting of any result is prohibited",
               "Data use",
               "is",
               "restricted",
               "researchers",
               "studying",
               "Consent Group 1",
               "Consent Group 2",
               "National law prohibits individual level data from being deposited. Summary-level statistics can be provided",
               "The Regents of the University of California San Francisco"
               ]

keyList2 = ["GRU",
            "General Research",
            "General Research Use",
            "Research",
            "Health Research",
            "Medical Research",
            "Biomedical Research",
            "HMB",
            "Health medical biomedical research",
            "health/medical/biomedcal research",
            "health/medical/biomedical"]

keyList1 = ["Disease",
           "Disorder"]